### ISSUE TITLE
Possible merge

### ISSUE THREAD

**Issue by thunderer** [maiorano84/shortcodes#1]
Hi, I also wrote a [shortcode library](https://github.com/thunderer/Shortcode) which is battle-tested and used in production. I see that your project is quite new so maybe rather than solving same problems once again you could use my code or join the project? I'd be happy to discuss and implement any ideas you may have, please just report an issue or submit Pull Request. What would you say?

**Comment by maiorano84** [comment]
Thank you for reaching out.

I've taken a look at your project, and while I appreciate what you're trying to achieve, I think I'll pass on the offer.

**Comment by thunderer** [comment]
No problem, if I could be of any help in the future, let me know.
