### ISSUE TITLE
Feature Request - default handler

### ISSUE THREAD

**Issue by garyns** [maiorano84/shortcodes#2]
Hi,
Nice library. I evaluated a few php libs and yours was the simplest to use and best documented.

One feature I'm missing is a default handler for shortcodes. I have a dynamic array of key/values that I'd like to use as shortcodes in a simple templating engine.

Cheers
Gary.

**Comment by maiorano84** [comment]
I'm not opposed to fleshing things out a bit. Can you clarify what you mean exactly when you say you need a default handler?

If you mean that you want to render out shortcode tags using a default shortcode class or SimpleShortcode instance regardless of whether or not they've been registered, you can do that relatively easily by extending the default ShortcodeManager.

Something like this might work:

```
use Maiorano\Shortcodes\Manager\ShortcodeManager;
use Maiorano\Shortcodes\Exceptions\RegisterException;
class MyManager extends ShortcodeManager{
    public function doShortcode($content, $tags = [], $deep = false){
        $tags = $tags ?: $this->getRegistered(); 
        $content = $this->parser->parseShortcode($content, $tags, function ($tag, $content, $atts) {
            try{
                $shortcode = $this[$tag];
            }
            catch(RegisterException $e){
                $shortcode = MyDefaultShortcode($tag); //Set $name in __construct?
            }
            if ($shortcode instanceof AttributeInterface) {
                $atts = array_merge($shortcode->getAttributes(), $atts);
            }
            return $shortcode->handle($content, $atts);
        });
        return $deep ? $this->doShortcode($content, $tags, $deep) : $content;
    }
}
```

Granted, that's more of a gist than an actual working implementation, but that should give you an idea in terms of how you can approach it.

Let me know if that helps, or if I'm way off track.

**Comment by maiorano84** [comment]
Closed due to inactivity.
